

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
from = "/404/:splat"
to = "https://bartyspacelabs.tech/404"
status = 404

[[redirects]]
from = ":scheme://www.bartyspacelabs.tech/*"
to = "https://bartyspacelabs.tech/:splat"
status = 302  

[[redirects]]
from = ":scheme://www.bartyspacelabs.tech/*"
to = "https://bartyspacelabs.tech/:splat"
status = 302

[[redirects]]
from = "https://bartyspacelabs.netlify.app/*"
to = "https://bartyspacelabs.tech/:splat"
status = 301